/* Generated By:JavaCC: Do not edit this line. VNMEval.java Version 7.0.9 */
public class VNMEval implements VNMVisitor{
  public Object defaultVisit(SimpleNode node, Object data) throws Exception{
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTbody node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTclause node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTvar_decl node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTfn_decl node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTident_list node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTfn_call node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTboolean_call node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTexp_list node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTcondition_list node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTReturn node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  
  // printing stuff
  public Object visit(ASTPrint node, Object data) throws Exception{
    int children = node.jjtGetNumChildren();
    for (int i=0; i<children; i++) {
      Object res = node.jjtGetChild(i).jjtAccept(this,null);
      if (res != null) System.out.print(res);
    }
		return null;
  }
  // print line
  public Object visit(ASTPrint_ln node, Object data) throws Exception{
    int children = node.jjtGetNumChildren();
    for (int i=0; i<children; i++) {
      Object res = node.jjtGetChild(i).jjtAccept(this,null);
      if (res != null) System.out.print(res);
    }
    System.out.println("");
    return null;
  }
  
  public Object visit(ASTAssign node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  // if statement logic
  public Object visit(ASTIf node, Object data) throws Exception{
    Boolean condition = (Boolean) node.jjtGetChild(0).jjtAccept(this, data);
    if (condition) {
        return node.jjtGetChild(1).jjtAccept(this, data);
    } else {
        Node elseNode = node.jjtGetChild(2);
        if (elseNode instanceof ASTNULL) {
            return null;
        }
        return elseNode.jjtAccept(this, data);
    }
  }
  public Object visit(ASTNULL node, Object data) throws Exception{
    return null;
  }
  public Object visit(ASTFor node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTWhile node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTor node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTand node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTnot node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  // compare numbers
  public Object visit(ASTcomparison node, Object data) throws Exception{
    Object left = node.jjtGetChild(0).jjtAccept(this, data);
    Node comparator = node.jjtGetChild(1);
    Object right = node.jjtGetChild(2).jjtAccept(this, data);
    
    if (left instanceof Integer && right instanceof Integer) {
        int l = (Integer)left;
        int r = (Integer)right;
        if (comparator instanceof ASTle) return l < r;
        if (comparator instanceof ASTleq) return l <= r;
        if (comparator instanceof ASTgre) return l > r;
        if (comparator instanceof ASTgeq) return l >= r;
        if (comparator instanceof ASTeq) return l == r;
        if (comparator instanceof ASTneq) return l != r;
    }
    return false;
  }
  public Object visit(ASTle node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTleq node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTgre node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTgeq node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTeq node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTneq node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTin node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTnotin node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  // sum logic
  public Object visit(ASTsum node, Object data) throws Exception{
    int children = node.jjtGetNumChildren();
    int sum = 0;
    for (int i=0; i<children; i++) {
        Object res = node.jjtGetChild(i).jjtAccept(this, data);
        if (res instanceof Integer) {
            sum += (Integer)res;
        } else {
            throw new RuntimeException("Type mismatch in sum: expected Integer");
        }
    }
    return sum;
  }
  // make negative
  public Object visit(ASTneg node, Object data) throws Exception{
    Object child = node.jjtGetChild(0).jjtAccept(this, data);
    if (child instanceof Integer) {
        return -((Integer)child);
    }
    throw new RuntimeException("Type mismatch in neg: expected Integer");
  }
  public Object visit(ASTpos node, Object data) throws Exception{
    return node.jjtGetChild(0).jjtAccept(this, data);
  }
  // multiply
  public Object visit(ASTmul node, Object data) throws Exception{
    Object left = node.jjtGetChild(0).jjtAccept(this, data);
    Object right = node.jjtGetChild(1).jjtAccept(this, data);
    return (Integer)left * (Integer)right;
  }
  // divide
  public Object visit(ASTdiv node, Object data) throws Exception{
    Object left = node.jjtGetChild(0).jjtAccept(this, data);
    Object right = node.jjtGetChild(1).jjtAccept(this, data);
    return (Integer)left / (Integer)right;
  }
  // modulo
  public Object visit(ASTmod node, Object data) throws Exception{
    Object left = node.jjtGetChild(0).jjtAccept(this, data);
    Object right = node.jjtGetChild(1).jjtAccept(this, data);
    return (Integer)left % (Integer)right;
  }
  public Object visit(ASTvec_const node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  // return true
  public Object visit(ASTTRUE node, Object data) throws Exception{
    return true;
  }
  // return false
  public Object visit(ASTFALSE node, Object data) throws Exception{
    return false;
  }
  public Object visit(ASTidvec node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTidnum node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  public Object visit(ASTidbool node, Object data) throws Exception{
    return defaultVisit(node, data);
  }
  // parse int
  public Object visit(ASTnumber node, Object data) throws Exception{
    Object val = node.jjtGetValue();
    if (val instanceof Integer) return val;
    return Integer.parseInt(val.toString());
  }
  // get string value
  public Object visit(ASTstring node, Object data) throws Exception{
    Object val = node.jjtGetValue();
    String s = val.toString();
   
    if (s.startsWith("\"") && s.endsWith("\"")) {
        return s.substring(1, s.length()-1);
    }
    return s;
  }
}
/* JavaCC - OriginalChecksum=22d58c5389ead436110ed9c53d7f4358 (do not edit this line) */
